
services:
  db:
    image: mariadb:10.5.8
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      #MYSQL_DATABASE: pwtriptales_db
      #MYSQL_USER: root
      #MYSQL_PASSWORD: rootroot
    expose:
      - "3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  web:
    image: python:3.9.22
    ports:
      - "8004:8000"
    volumes:
      - .:/usr/app
    working_dir: /usr/app
    command: >
      sh -c "sleep 5 &&
             pip install --no-cache-dir -r requirements.txt &&
             python manage.py migrate &&
             python manage.py createsuperuser &&
             python manage.py create_initial_data &&
             python manage.py runserver 0.0.0.0:8080 >> log.log 2>&1"
    depends_on:
      - db